### ISSUE TITLE
Load configuration form appsettings.json

### ISSUE THREAD

**Issue by code-sport** [kmcclellan/kafka-hosting#3]
Is the a possibility to load for example the ProducerConfig from the appsettings.json with the ConfigurationManager?

**Comment by kmcclellan** [comment]
Typically, yes. Most of the time you are working with `IServiceCollection` you'll also have an `IConfiguration` instance that should be bound to `appsettings.json`. If using [`IHostBuilder`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostbuilder), it will be on the `HostBuilderContext` of `ConfigureServices(...)`:

```c#
var builder = Host.CreateDefaultBuilder()
    .ConfigureServices(
        (context, services) =>
        {
            var config = context.Configuration.GetSection("Kafka")
                .Get<ProducerConfig>();

            services.AddKafkaClient(config);
        });
```

Your `appsettings.json` would need to match the properties of [`ProducerConfig`](https://docs.confluent.io/platform/current/clients/confluent-kafka-dotnet/_site/api/Confluent.Kafka.ProducerConfig.html).

```json
{
  "Kafka": {
    "BootstrapServers": "localhost:9092"
    // etc...
  }
}
```

Personally, I prefer to bypass the model when loading from config and use the names from [librdkafka](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). You just need to enumerate instead of binding:

```c#
var config = context.Configuration.GetSection("Kafka")
    .AsEnumerable(makePathsRelative: true);
```

```json
{
  "Kafka": {
    "bootstrap.servers": "localhost:9092"
    // etc...
  }
}
```

Of course, retrieving configuration while configuring your container doesn't work for all scenarios (like lazy config and reloading). For these less common scenarios, I might suggest injecting an `IKafkaFactory`.

**Comment by kmcclellan** [comment]
In v3, configuration is now bound automatically.
